packages:
  libfabric:
    buildable: false
    externals:
    - spec: libfabric@1.15.0.0
  slurm:
    buildable: false
    externals:
    - spec: slurm@20-11-8-1
      prefix: /usr
  rdma-core:
    buildable: false
    externals:
    - spec: rdma-core@39.1
      prefix: /usr
  xpmem:
    buildable: false
    externals:
    - spec: xpmem@0.29.2
      prefix: /opt/cray/xpmem/2.2.40-2.1_2.56__g3cf3325.shasta
